Modified makefile.  Seperate targets for 'chez' and 'ws'/'ws.opt'.
Uses the REGIMENT_OR_WAVESCRIPT environment variable.

diff --git a/src/bin/ws b/src/bin/ws
--- a/src/bin/ws
+++ b/src/bin/ws
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-TMP=/tmp/`whoami`/wavescript_parsed.tmp
+#TMP=/tmp/`whoami`/wavescript_parsed.tmp
 
 if [ ! -f "$1" ];
 then echo Usage: "ws <file> <options ...>";
@@ -8,17 +8,22 @@ then echo Usage: "ws <file> <options ...>";
      exit 1;
 fi
 
-if [ ! -d /tmp/`whoami` ]; 
-then mkdir /tmp/`whoami`;
-fi
+# if [ ! -d /tmp/`whoami` ]; 
+# then mkdir /tmp/`whoami`;
+# fi
 
 
-if [ ! `which wsparse` ]
-then echo \"wsparse\" command not found.  Compile it!
-     exit 1;
-fi
+# if [ ! `which wsparse` ]
+# then echo \"wsparse\" command not found.  Compile it!
+#      exit 1;
+# fi
 
-wsparse $1 --nopretty > $TMP
-wsint $TMP ${1+"$@"}; 
-rm -f $TMP
+#wsparse $1 --nopretty > $TMP
+#regiment wsint $TMP ${1+"$@"}; 
+#rm -f $TMP
 
+D=`dirname "$1"`
+B=`basename "$1"`
+abspath="`cd \"$D\" 2>/dev/null && pwd || echo \"$D\"`/$B"
+
+regiment wsint $abspath ${1+"$@"}; 
