Ok, got an improved version of socket_out.
It can now handle establishing multiple connections from a process.  It currently spawns servers in parallel but connects clients serially.  socket_out doesn't block and dumps data, and socket_in currently blocks.  

Socken_in is still run by a timer, which is incorrect.

Now example3.ws works.  But cycles will cause problems.

diff --git a/src/bin/wsc b/src/bin/wsc
--- a/src/bin/wsc
+++ b/src/bin/wsc
@@ -118,16 +118,19 @@ rm -f "$OUTFILE"
 if [ "$REGFLAG" == "" ]; then REGFLAG=wscomp; fi
 export REGIMENT_OR_WAVESCRIPT=WS
 
-echo "$REGIMENTEXEC" $REGFLAG $abspath $REGPASSTHRU ;
 
+#================================================================================
+
+echo "$REGIMENTEXEC" $REGFLAG $abspath $REGPASSTHRU ;
 if "$REGIMENTEXEC" $REGFLAG $abspath $REGPASSTHRU ;
 then echo 
 else #rm -f $TMP; 
-    echo Compilation aborted: \"$REGIMENTEXEC $REGFLAG\" exited with error code.
-    exit 1;
+    CODE=$?;
+    echo Compilation aborted: \"$REGIMENTEXEC $REGFLAG\" exited with error code $CODE.
+    exit $CODE;
 fi
 
-
+#================================================================================
 
 if [ "$WSARCH" == "ensbox" ];
 then CCOMPILE='wsc-arm-g++'
