Applying various fixes to the shell scripts. Added some simple example of socket-using programs, including one that uses sockets and wsqlib.ws I introduced a test script for reuters/example.ws, but wsc2 doesn't yet work with all the queries in that file.

diff --git a/src/bin/wsc b/src/bin/wsc
--- a/src/bin/wsc
+++ b/src/bin/wsc
@@ -120,11 +120,13 @@ export REGIMENT_OR_WAVESCRIPT=WS
 echo "$REGIMENTEXEC" $REGFLAG $abspath $REGPASSTHRU ;
 
 if "$REGIMENTEXEC" $REGFLAG $abspath $REGPASSTHRU ;
-then echo
+then echo ERROR CODE $?
 else #rm -f $TMP; 
-    echo Compilation aborted: \"regiment wscomp\" exited with error code.
+    echo Compilation aborted: \"$REGIMENTEXEC $REGFLAG\" exited with error code.
     exit 1;
 fi
+
+
 
 if [ "$WSARCH" == "ensbox" ];
 then CCOMPILE='wsc-arm-g++'
