Changed opencv to no longer depend on marshaling tuples/structs, or on allocating strings/arrays on the C side.  Now it works with MLton.  (Subsequently I did add the ability to allocate mono arrays on the C side with mlton.)
The bgsub4 implementation is at the point where it generates output that looks good to the eye.  It 
doesn't match exactly, and it seems to get further off as it proceeds, which is consistent with the 
fact that it doesn't update the bg histogram on the fly yet.

diff --git a/src/bin/wsmlton-secondphase b/src/bin/wsmlton-secondphase
--- a/src/bin/wsmlton-secondphase
+++ b/src/bin/wsmlton-secondphase
@@ -16,7 +16,7 @@ if   [ "$WSMLOUTPUT" == "" ]; then WSMLOUTPUT=query.mlton.exe; fi
 # Clean up first:
 rm -f "$WSMLOUTPUT"
 
-export MLTONARGS="$MLTONARGS -verbose 1 -link-opt -lfftw3f -cc-opt -I$REGIMENTD/src/linked_lib "
+export MLTONARGS="$MLTONARGS -verbose 1 -link-opt -lfftw3f -cc-opt -DWSMLTON -cc-opt -I$REGIMENTD/src/linked_lib "
 export WSMLCINCLUDES="$WSMLCINCLUDES $REGIMENTD/src/ws/passes/mlton_bkend/fftw.c "
 
 # I'm having a lot of trouble getting enough quotes around 
@@ -46,12 +46,17 @@ then
    echo 
    #export WSMLCINCLUDES="$WSMLCINCLUDES $EXTRALIBS"
    for inc in $EXTRALIBS; do 
-     if [ -f "$inc" ];
+
+     if [ "${inc#*.}" = "so" ];
+     then BASENAME=${inc%.*}
+          MLTONARGS+=" -link-opt -l${BASENAME#lib} "
+     elif [ -f "$inc" ];
      then WSMLCINCLUDES+=" $inc "
      elif [ -f "$REGIMENTD/lib/$inc" ];
      then WSMLCINCLUDES+=" $REGIMENTD/lib/$inc "; 
-     else echo "Couldn't locate include $inc"; 
-          exit 1
+     else 
+     #WSMLCINCLUDES+=" $inc "
+     echo "Couldn't locate include $inc"; exit 1
      fi
    done
    export WSMLCINCLUDES
