Started porting eugene's application.
Made a significant phase-order change to the compiler.  I moved remove-complex constant before 
degeneralize-arithmetic -- this avoids a problem with polymorphic numbers embedded inside complex constants.

This refactoring isn't well tested yet though....

diff --git a/src/bin/wstiny b/src/bin/wstiny
--- a/src/bin/wstiny
+++ b/src/bin/wstiny
@@ -71,16 +71,23 @@ function pc() {
    wsc2-gcc;
 }
 
+# A default:
+if [ "$THEMOTE" == "" ]; then THEMOTE=/dev/ttyUSB0; fi
+
 # This builds both... for now this is only for telos:
 if [ -f "WSQuery.nc" ] && 
    [ -f "query.c" ]; 
 then
-  echo;echo "BUILDING SPLIT APPLICATION (TELOS/PC), first Telos:"
+  echo;echo "BUILDING SPLIT APPLICATION (TELOS/PC)"
+  pc;
+  echo;echo "BUILDING TINYOS COMPONENTS:" 
   echo "============================================================"
   #ps aux | grep java
   killjavahack
-  make -f Makefile.tos2 telosb install 2> .TOS_build_log.txt
-  pc;
+  
+  if ! make -f Makefile.tos2 telosb bsl,$THEMOTE install 2> .TOS_build_log.txt
+  then echo "Error $? while building telosb, see .TOS_build_log.txt"; exit 1;
+  fi 
 elif [ -f "WSQuery.nc" ]; 
 then tossim;
   
