Change marmot data download script

diff --git a/src/demos/wavescope/download_sample_marmot_data b/src/demos/wavescope/download_sample_marmot_data
--- a/src/demos/wavescope/download_sample_marmot_data
+++ b/src/demos/wavescope/download_sample_marmot_data
@@ -5,9 +5,12 @@ then echo "Already present!"
      exit 0
 fi
 
+# URL=http://www.regiment.us/marmotdata/6sec_marmot_sample.raw
+URL=http://cs.indiana.edu/~rrnewton/datasets/marmotdata/6sec_marmot_sample.raw
+
 if [ `which wget` ];
-then wget www.regiment.us/marmotdata/6sec_marmot_sample.raw
+then wget $URL
 elif [ `which curl` ];
-then curl "http://www.regiment.us/marmotdata/6sec_marmot_sample.raw" -o 6sec_marmot_sample.raw
-else echo NEITHER CURL NOR WGET AVAILABLE!!; exit 1
+then curl "$URL" -o 6sec_marmot_sample.raw
+else echo "NEITHER CURL NOR WGET AVAILABLE!!  Cannot download."; exit 1
 fi 
